/*
 * The MIT License
 *
 * Copyright 2021 Andrey Gheno Piekas
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package br.com.nextlevel.view;

import br.com.nextlevel.jdbc.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import br.com.nextlevel.view.TelaProduto;

/**
 *
 * @author Andrey Gheno Piekas
 */
public class TelaPedidos extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form TelaPedidos2
     */
    public TelaPedidos() {
        initComponents();
        conexao = ConnectionFactory.getConnection();
    }

//    private void setar_campos() {
//        int setar = TelaPedidosTABLEPRODUTOS.getSelectedRow();
//        TelaProduto.se (TelaPedidosTABLEPRODUTOS.getModel().getValueAt(setar, 1).toString());
//        TelaClientesNOME.setText(TelaPedidosTABLEPRODUTOS.getModel().getValueAt(setar, 2).toString());
//        TelaClientesEMAIL.setText(TelaPedidosTABLEPRODUTOS.getModel().getValueAt(setar, 3).toString());
//        TelaClientesCPF.setText(TelaPedidosTABLEPRODUTOS.getModel().getValueAt(setar, 4).toString());
//        TelaClientesTELEFONE.setText(TelaPedidosTABLEPRODUTOS.getModel().getValueAt(setar, 5).toString());
//        TelaClientesENTREGA.setText(TelaPedidosTABLEPRODUTOS.getModel().getValueAt(setar, 6).toString());
//        
//        TelaPedidosTABLEPRODUTOS.getSelectedRow(TelaProdutoID);
//
//
//        ///
//        TelaPedidosBUTTONADICIONAR.setEnabled(false);
//
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TelaPedidosNUMEROPEDIDO = new javax.swing.JTextField();
        TelaPedidosDATA = new javax.swing.JTextField();
        TelaPedidosORCAMENTO = new javax.swing.JRadioButton();
        TelaPedidosORDEM = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        TelaPedidosCOMBOSITUACAO = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TelaPedidosCLIENTEPESQUISAR = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TelaPedidosIDPESQUISAR = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TelaPedidosTABLECLIENTE = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        TelaPedidosBUTTONADICIONAR = new javax.swing.JButton();
        TelaPedidosBUTTONREMOVER = new javax.swing.JButton();
        TelaPedidosBUTTONEDITAR = new javax.swing.JButton();
        TelaPedidosBUTTONPESQUISAR = new javax.swing.JButton();
        TelaPedidosBUTTONIMPRIMIR = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TelaPedidosTABLEPRODUTOS = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pedidos");
        setPreferredSize(new java.awt.Dimension(673, 583));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Pedido");

        jLabel2.setText("Data");

        TelaPedidosNUMEROPEDIDO.setEditable(false);
        TelaPedidosNUMEROPEDIDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelaPedidosNUMEROPEDIDOActionPerformed(evt);
            }
        });

        TelaPedidosDATA.setEditable(false);

        buttonGroup1.add(TelaPedidosORCAMENTO);
        TelaPedidosORCAMENTO.setText("Orcamento");
        TelaPedidosORCAMENTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelaPedidosORCAMENTOActionPerformed(evt);
            }
        });

        buttonGroup1.add(TelaPedidosORDEM);
        TelaPedidosORDEM.setText("Ordem");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(TelaPedidosNUMEROPEDIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelaPedidosORCAMENTO))
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TelaPedidosORDEM)
                    .addComponent(TelaPedidosDATA, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelaPedidosNUMEROPEDIDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelaPedidosDATA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelaPedidosORCAMENTO)
                    .addComponent(TelaPedidosORDEM)))
        );

        jLabel3.setText("Situacao");

        TelaPedidosCOMBOSITUACAO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/nextlevel/icones/pesquisar.png"))); // NOI18N

        jLabel5.setText("* ID");

        TelaPedidosIDPESQUISAR.setEditable(false);

        TelaPedidosTABLECLIENTE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Fone"
            }
        ));
        jScrollPane1.setViewportView(TelaPedidosTABLECLIENTE);

        jLabel6.setText("Cliente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TelaPedidosCLIENTEPESQUISAR, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(TelaPedidosIDPESQUISAR, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TelaPedidosIDPESQUISAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TelaPedidosCLIENTEPESQUISAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        TelaPedidosBUTTONADICIONAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/nextlevel/icones/create.png"))); // NOI18N
        TelaPedidosBUTTONADICIONAR.setToolTipText("Novo Pedido");
        TelaPedidosBUTTONADICIONAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TelaPedidosBUTTONADICIONAR.setPreferredSize(new java.awt.Dimension(60, 60));

        TelaPedidosBUTTONREMOVER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/nextlevel/icones/delete.png"))); // NOI18N
        TelaPedidosBUTTONREMOVER.setToolTipText("Excluir Pedido");
        TelaPedidosBUTTONREMOVER.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TelaPedidosBUTTONREMOVER.setPreferredSize(new java.awt.Dimension(60, 60));

        TelaPedidosBUTTONEDITAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/nextlevel/icones/edit.png"))); // NOI18N
        TelaPedidosBUTTONEDITAR.setToolTipText("Editar Pedido");
        TelaPedidosBUTTONEDITAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TelaPedidosBUTTONEDITAR.setPreferredSize(new java.awt.Dimension(60, 60));

        TelaPedidosBUTTONPESQUISAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/nextlevel/icones/search.png"))); // NOI18N
        TelaPedidosBUTTONPESQUISAR.setToolTipText("Pesquisar Pedido");
        TelaPedidosBUTTONPESQUISAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TelaPedidosBUTTONPESQUISAR.setPreferredSize(new java.awt.Dimension(60, 60));

        TelaPedidosBUTTONIMPRIMIR.setText("REL");
        TelaPedidosBUTTONIMPRIMIR.setToolTipText("Imprimir Pedido");
        TelaPedidosBUTTONIMPRIMIR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TelaPedidosBUTTONIMPRIMIR.setPreferredSize(new java.awt.Dimension(60, 60));
        TelaPedidosBUTTONIMPRIMIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelaPedidosBUTTONIMPRIMIRActionPerformed(evt);
            }
        });

        TelaPedidosTABLEPRODUTOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TelaPedidosTABLEPRODUTOS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(TelaPedidosBUTTONADICIONAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TelaPedidosBUTTONEDITAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TelaPedidosBUTTONREMOVER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TelaPedidosBUTTONPESQUISAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TelaPedidosCOMBOSITUACAO, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(TelaPedidosBUTTONIMPRIMIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TelaPedidosCOMBOSITUACAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TelaPedidosBUTTONEDITAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelaPedidosBUTTONADICIONAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelaPedidosBUTTONREMOVER, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelaPedidosBUTTONPESQUISAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelaPedidosBUTTONIMPRIMIR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setBounds(0, 0, 910, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void TelaPedidosNUMEROPEDIDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelaPedidosNUMEROPEDIDOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelaPedidosNUMEROPEDIDOActionPerformed

    private void TelaPedidosORCAMENTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelaPedidosORCAMENTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelaPedidosORCAMENTOActionPerformed

    private void TelaPedidosBUTTONIMPRIMIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelaPedidosBUTTONIMPRIMIRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelaPedidosBUTTONIMPRIMIRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TelaPedidosBUTTONADICIONAR;
    private javax.swing.JButton TelaPedidosBUTTONEDITAR;
    private javax.swing.JButton TelaPedidosBUTTONIMPRIMIR;
    private javax.swing.JButton TelaPedidosBUTTONPESQUISAR;
    private javax.swing.JButton TelaPedidosBUTTONREMOVER;
    private javax.swing.JTextField TelaPedidosCLIENTEPESQUISAR;
    private javax.swing.JComboBox<String> TelaPedidosCOMBOSITUACAO;
    private javax.swing.JTextField TelaPedidosDATA;
    private javax.swing.JTextField TelaPedidosIDPESQUISAR;
    private javax.swing.JTextField TelaPedidosNUMEROPEDIDO;
    private javax.swing.JRadioButton TelaPedidosORCAMENTO;
    private javax.swing.JRadioButton TelaPedidosORDEM;
    private javax.swing.JTable TelaPedidosTABLECLIENTE;
    private javax.swing.JTable TelaPedidosTABLEPRODUTOS;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
