/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package antigos;

/**
 *
 * @author Andrey Gheno Piekas
 */
public class TelaFuncionariosOLD extends javax.swing.JFrame {

    /**
     * Creates new form TelaFuncionarios
     */
    public TelaFuncionariosOLD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaFuncionariosID = new javax.swing.JLabel();
        TelaFuncionariosFIELDID = new javax.swing.JTextField();
        TelaFuncionariosNOME = new javax.swing.JLabel();
        TelaFuncionariosFieldNOME = new javax.swing.JTextField();
        TelaFuncionariosEMAIL = new javax.swing.JLabel();
        TelaFuncionariosFieldEMAIL = new javax.swing.JTextField();
        TelaFuncionariosTELEFONE = new javax.swing.JLabel();
        TelaFuncionariosENDERECO = new javax.swing.JLabel();
        TelaFuncionariosFieldENDERECO = new javax.swing.JTextField();
        TelaFuncionariosFieldBAIRRO = new javax.swing.JTextField();
        TelaFuncionariosBAIRRO = new javax.swing.JLabel();
        TelaFuncionariosFieldTELEFONE = new javax.swing.JFormattedTextField();
        TelaFuncionariosFieldCIDADE = new javax.swing.JTextField();
        TelaFuncionariosCIDADE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Funcionários");
        setResizable(false);

        TelaFuncionariosID.setText("ID");

        TelaFuncionariosNOME.setText("Nome");

        TelaFuncionariosEMAIL.setText("Email");

        TelaFuncionariosTELEFONE.setText("Telefone");

        TelaFuncionariosENDERECO.setText("Endereço");

        TelaFuncionariosBAIRRO.setText("Bairro");

        try {
            TelaFuncionariosFieldTELEFONE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        TelaFuncionariosCIDADE.setText("Cidade");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TelaFuncionariosID)
                                .addGap(18, 18, 18)
                                .addComponent(TelaFuncionariosFIELDID, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TelaFuncionariosNOME)
                                .addGap(18, 18, 18)
                                .addComponent(TelaFuncionariosFieldNOME, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(TelaFuncionariosEMAIL)
                                .addGap(18, 18, 18)
                                .addComponent(TelaFuncionariosFieldEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(TelaFuncionariosTELEFONE)
                                .addGap(18, 18, 18)
                                .addComponent(TelaFuncionariosFieldTELEFONE, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(TelaFuncionariosENDERECO)
                                .addGap(18, 18, 18)
                                .addComponent(TelaFuncionariosFieldENDERECO)))
                        .addGap(86, 86, 86))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TelaFuncionariosBAIRRO)
                        .addGap(18, 18, 18)
                        .addComponent(TelaFuncionariosFieldBAIRRO, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TelaFuncionariosCIDADE)
                        .addGap(18, 18, 18)
                        .addComponent(TelaFuncionariosFieldCIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelaFuncionariosID)
                    .addComponent(TelaFuncionariosFIELDID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelaFuncionariosFieldNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelaFuncionariosNOME))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelaFuncionariosEMAIL)
                    .addComponent(TelaFuncionariosFieldEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelaFuncionariosTELEFONE)
                    .addComponent(TelaFuncionariosFieldTELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelaFuncionariosENDERECO)
                    .addComponent(TelaFuncionariosFieldENDERECO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TelaFuncionariosFieldCIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TelaFuncionariosCIDADE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TelaFuncionariosFieldBAIRRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TelaFuncionariosBAIRRO)))
                .addContainerGap(272, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionariosOLD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionariosOLD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionariosOLD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionariosOLD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionariosOLD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TelaFuncionariosBAIRRO;
    private javax.swing.JLabel TelaFuncionariosCIDADE;
    private javax.swing.JLabel TelaFuncionariosEMAIL;
    private javax.swing.JLabel TelaFuncionariosENDERECO;
    private javax.swing.JTextField TelaFuncionariosFIELDID;
    private javax.swing.JTextField TelaFuncionariosFieldBAIRRO;
    private javax.swing.JTextField TelaFuncionariosFieldCIDADE;
    private javax.swing.JTextField TelaFuncionariosFieldEMAIL;
    private javax.swing.JTextField TelaFuncionariosFieldENDERECO;
    private javax.swing.JTextField TelaFuncionariosFieldNOME;
    private javax.swing.JFormattedTextField TelaFuncionariosFieldTELEFONE;
    private javax.swing.JLabel TelaFuncionariosID;
    private javax.swing.JLabel TelaFuncionariosNOME;
    private javax.swing.JLabel TelaFuncionariosTELEFONE;
    // End of variables declaration//GEN-END:variables
}
